sonar.projectKey=maustin44_mcp-sec-demo
sonar.organization=maustin44

# Source directories
sonar.sources=app
sonar.exclusions=app/node_modules/**,app/package-lock.json

# Language
sonar.javascript.lcov.reportPaths=app/coverage/lcov.info

# SonarCloud endpoint
sonar.host.url=https://sonarcloud.io
